import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Compiled Sanity Studio, written by `sanity build` / `sanity deploy`.
    "dist/**",
    // Generated by `sanity typegen`; overwritten on every run, so lint fixes can't stick.
    "src/sanity/types.ts",
  ]),
]);

export default eslintConfig;
