/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CodeNote = {
  _id: string;
  _type: "codeNote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  url: string;
  blurb: string;
  language: string;
};

export type Writing = {
  _id: string;
  _type: "writing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  url: string;
  published: string;
};

export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  company: string;
  start: string;
  end?: string;
  summary: string;
  order: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug?: Slug;
  order: number;
  featured?: boolean;
  metric?: {
    value: string;
    label: string;
    source: string;
  };
  failureMode: string;
  scope: "Solo" | "Team of 2" | "Team of 3" | "Team of 5" | "Team of 8+";
  stack: Array<string>;
  media?: {
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt: string;
  };
  liveUrl?: string;
  repoUrl?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2";
        listItem?: never;
        markDefs?: Array<{
          href: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        filename: string;
        language: string;
        code: string;
        _type: "codeBlock";
        _key: string;
      }
    | {
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt?: string;
        caption?: string;
        _type: "figure";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline: string;
  evidence: Array<string>;
  heroMetric: {
    value: string;
    label: string;
    source: string;
  };
  ctaLabel: string;
  ctaTarget: string;
  about: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  stack: Array<{
    group: string;
    items: Array<string>;
    _key: string;
  }>;
  contactIntro: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  location?: string;
  timezone: string;
  yearsExperience: string;
  availability: string;
  email: string;
  githubUrl?: string;
  linkedinUrl?: string;
  resumeFile: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  lastUpdated: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CodeNote
  | Writing
  | Role
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Home
  | SanityFileAssetReference
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: WORK_INDEX_QUERY
// Query: *[_type == "project"] | order(order asc) {    _id,    title,    "slug": slug.current,    order,    featured,    metric,    failureMode,    scope,    stack,    liveUrl,    repoUrl,    media { alt, image { asset->{ url } } }  }
export type WORK_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string | null;
  order: number;
  featured: boolean | null;
  metric: {
    value: string;
    label: string;
    source: string;
  } | null;
  failureMode: string;
  scope: "Solo" | "Team of 2" | "Team of 3" | "Team of 5" | "Team of 8+";
  stack: Array<string>;
  liveUrl: string | null;
  repoUrl: string | null;
  media: {
    alt: string;
    image: {
      asset: {
        url: string;
      } | null;
    };
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] {    name,    location,    timezone,    yearsExperience,    availability,    email,    githubUrl,    linkedinUrl,    "resumeUrl": resumeFile.asset->url,    lastUpdated  }
export type SITE_SETTINGS_QUERY_RESULT = {
  name: string;
  location: string | null;
  timezone: string;
  yearsExperience: string;
  availability: string;
  email: string;
  githubUrl: string | null;
  linkedinUrl: string | null;
  resumeUrl: string | null;
  lastUpdated: string;
} | null;

// Source: src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: *[_type == "home" && _id == "home"][0] {    headline,    evidence,    heroMetric,    ctaLabel,    ctaTarget,    about,    stack[] { _key, group, items },    contactIntro  }
export type HOME_QUERY_RESULT = {
  headline: string;
  evidence: Array<string>;
  heroMetric: {
    value: string;
    label: string;
    source: string;
  };
  ctaLabel: string;
  ctaTarget: string;
  about: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  stack: Array<{
    _key: string;
    group: string;
    items: Array<string>;
  }>;
  contactIntro: string;
} | null;

// Source: src/sanity/queries.ts
// Variable: ROLES_QUERY
// Query: *[_type == "role"] | order(order asc) {    _id,    title,    company,    start,    end,    summary  }
export type ROLES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  company: string;
  start: string;
  end: string | null;
  summary: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(order asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    order,\n    featured,\n    metric,\n    failureMode,\n    scope,\n    stack,\n    liveUrl,\n    repoUrl,\n    media { alt, image { asset->{ url } } }\n  }\n': WORK_INDEX_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    name,\n    location,\n    timezone,\n    yearsExperience,\n    availability,\n    email,\n    githubUrl,\n    linkedinUrl,\n    "resumeUrl": resumeFile.asset->url,\n    lastUpdated\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "home" && _id == "home"][0] {\n    headline,\n    evidence,\n    heroMetric,\n    ctaLabel,\n    ctaTarget,\n    about,\n    stack[] { _key, group, items },\n    contactIntro\n  }\n': HOME_QUERY_RESULT;
    '\n  *[_type == "role"] | order(order asc) {\n    _id,\n    title,\n    company,\n    start,\n    end,\n    summary\n  }\n': ROLES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
